// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi9N50SqsMt4HJ7uPpdbaiEg7oMlRZ4Y0',
    appId: '1:355129313694:web:bf2fabd37ba0a565122e8f',
    messagingSenderId: '355129313694',
    projectId: 'translator-c1a5b',
    authDomain: 'translator-c1a5b.firebaseapp.com',
    storageBucket: 'translator-c1a5b.firebasestorage.app',
    measurementId: 'G-39ZSMSG1XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ron8wK77z1S4CpQXlep1XgdpxouR-2Q',
    appId: '1:355129313694:android:a8ab8162108b8eb0122e8f',
    messagingSenderId: '355129313694',
    projectId: 'translator-c1a5b',
    storageBucket: 'translator-c1a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1IWkCSNui49UVq52ES8UKJKrWkgLaWSg',
    appId: '1:355129313694:ios:efa55bdc548c34fc122e8f',
    messagingSenderId: '355129313694',
    projectId: 'translator-c1a5b',
    storageBucket: 'translator-c1a5b.firebasestorage.app',
    iosBundleId: 'com.example.translator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1IWkCSNui49UVq52ES8UKJKrWkgLaWSg',
    appId: '1:355129313694:ios:efa55bdc548c34fc122e8f',
    messagingSenderId: '355129313694',
    projectId: 'translator-c1a5b',
    storageBucket: 'translator-c1a5b.firebasestorage.app',
    iosBundleId: 'com.example.translator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi9N50SqsMt4HJ7uPpdbaiEg7oMlRZ4Y0',
    appId: '1:355129313694:web:20d4f0f03fcccda8122e8f',
    messagingSenderId: '355129313694',
    projectId: 'translator-c1a5b',
    authDomain: 'translator-c1a5b.firebaseapp.com',
    storageBucket: 'translator-c1a5b.firebasestorage.app',
    measurementId: 'G-LM02G1DXXV',
  );
}
